export interface LanguageStyleGuidance {
  everydayExamples: string[];
  keepNativeExamples: string[];
  notes?: string[];
}

const DEFAULT_GUIDANCE: LanguageStyleGuidance = {
  everydayExamples: [
    "last date",
    "deadline",
    "meeting",
    "project",
    "office",
    "appointment",
    "email",
    "online",
    "form",
    "application",
    "feedback",
    "timing",
    "plan",
    "update",
    "service",
    "ticket",
    "mobile",
    "charger",
    "internet",
    "wifi",
    "train",
    "metro",
    "station",
    "movie",
    "schedule",
    "holiday",
    "payment",
    "balance",
    "account",
    "document",
    "copy",
    "bill",
    "receipt"
  ],
  keepNativeExamples: [
    "common particles",
    "basic verbs",
    "pronouns",
    "numbers"
  ],
  notes: [
    "Borrowed English words should feel natural in local speech",
    "Core grammar must remain in the target language"
  ],
};

export const LANGUAGE_STYLE_GUIDANCE: Record<string, LanguageStyleGuidance> = {
  hi: {
    everydayExamples: [
      "last date",
      "deadline",
      "meeting",
      "project",
      "office",
      "admission",
      "form",
      "application",
      "academic year",
      "balance",
      "bank",
      "account",
      "payment",
      "online",
      "offline",
      "update",
      "schedule",
      "plan",
      "timing",
      "manager",
      "supervisor",
      "email",
      "message",
      "call",
      "phone",
      "mobile",
      "internet",
      "wifi",
      "charger",
      "service",
      "delivery",
      "ticket",
      "booking",
      "train",
      "metro",
      "bus pass",
      "meeting room",
      "maintenance",
      "deadline reminder",
      "status"
    ],
    keepNativeExamples: [
      "hai",
      "tha",
      "thi",
      "hun",
      "ho",
      "kya",
      "kyon",
      "kyunki",
      "main",
      "tum",
      "aap",
      "wo",
      "ye",
      "nahi",
      "ha",
      "ka",
      "ki",
      "ke",
      "se",
      "ko",
      "mein",
      "par",
      "aur",
      "lekin",
      "jab",
      "tab",
      "thoda",
      "zyada",
      "kal",
      "subah",
      "shaam"
    ],
    notes: [
      "Everyday Hindi should feel like Mumbai/Delhi street conversations with light English mixing",
      "Use English for formal nouns or modern objects, not for grammar or fillers"
    ],
  },
  kn: {
    everydayExamples: [
      "last date",
      "deadline",
      "meeting",
      "project",
      "office",
      "service",
      "payment",
      "online",
      "offline",
      "email",
      "message",
      "mobile",
      "phone",
      "charger",
      "internet",
      "wifi",
      "bus pass",
      "ticket",
      "booking",
      "metro",
      "train",
      "schedule",
      "plan",
      "update",
      "deadline reminder",
      "maintenance",
      "registration",
      "application",
      "balance",
      "account",
      "card",
      "document",
      "copy",
      "bill",
      "receipt"
    ],
    keepNativeExamples: [
      "idu",
      "idu",
      "illi",
      "alli",
      "yake",
      "yaake",
      "enu",
      "hege",
      "ninna",
      "nanna",
      "nivu",
      "navu",
      "olage",
      "horagade",
      "mele",
      "kelage",
      "illi",
      "alli",
      "haudu",
      "illa",
      "baruthe",
      "hodhitu",
      "madidira",
      "beku",
      "beda",
      "yaavaga",
      "yestu",
      "ondhu",
      "eradu"
    ],
    notes: [
      "Blend English for office/technology vocabulary while keeping Kannada structure intact",
      "Loanwords should match Bengaluru office and everyday life usage"
    ],
  },
};

export function getLanguageStyleGuidance(languageCode: string): LanguageStyleGuidance {
  return LANGUAGE_STYLE_GUIDANCE[languageCode] ?? DEFAULT_GUIDANCE;
}
